[package]
name = "server"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "doctavious-server"
path = "src/main.rs"

[dependencies]
axum = { workspace = true }
doctavious-server = { path = "../../lib/doctavious-server" }
tokio = { workspace = true }
tower-http = { workspace = true, features = ["timeout", "trace"] }
tracing-subscriber = { workspace = true, features = ["env-filter"] }

[build-dependencies]
built = "0.7"