#[package]
#name = "doctavious"
#version = "0.1.0"
#edition = "2021"
#
## See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
resolver = "2"
members = [
    "bin/doctavious",
    "lib/cifrs",
    "lib/doctavious-cli",
    "lib/doctavious-server",
    "lib/cas",
]

[workspace.dependencies]
anyhow = "1.0.70"
axum = { version = "0.6.18", features = ["headers", "http2", "macros", "multipart", "ws"] }
blake3 = "1.3.3"
chrono = {version="0.4",features = ["serde"]}
clap = { version = "4.0.32", features = ["derive"] }
dotenv = "0.15"
directories = "5.0.1"
figment = "0.10.11"
futures = "0.3.28"
git2 = "0.18.1"
glob = "0.3.0"
gray_matter = "0.2"
indexmap = { version = "2.0.2", features = ["serde"] }
lazy_static = "1.4"
mime = "0.3.17"
minijinja = "1.0.8"
once_cell = "1.17.1"
opendal = "0.42.0"
opentelemetry = { version = "0.21.0", features = ["rt-tokio", "trace"] }
opentelemetry-otlp = "0.14.0"
opentelemetry-semantic-conventions = "0.13.0"
regex = "1.8.4"
remain = "0.2.11"
reqwest = { version = "0.11.20", default-features = false, features = ["blocking", "rustls-tls", "json", "multipart"] }
serial_test = "2.0.0"
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
serde_json = { version = "1.0", features = ["preserve_order"] }
serde_regex = "1.1.0"
serde-xml-rs = "0.6.0"
serde_yaml = "0.9"
strum = { version = "0.25.0", features = ["derive"] }
swc_ecma_parser = "0.141.0"
swc = "0.269.58"
swc_common = { version = "0.33.0", features = ["tty-emitter"] }
swc_ecma_ast = { version = "0.110.0", features=["serde-impl"] }
temp-env = "0.3.1"
tempfile = "3.3.0"
thiserror = "1.0.30"
tokio = { version = "1.28", features = ["macros", "fs"] }
tokio-serde = { version = "0.8.0", features = ["json"] }
tokio-tungstenite = "0.20.1"
toml = "0.8.2"
tracing = { version = "0.1" }
tracing-opentelemetry = "0.22.0"
tracing-subscriber = { version = "0.3.17", features = ["env-filter", "std"] }
tracing-test = "0.2"
ulid = { version = "1.0.1", features = ["serde"] }
url = { version = "2.3.1", features = ["serde"] }
uuid = { version = "1.3.2", features = ["serde", "v4"] }
walkdir = "2.3.2"
which = "5.0.0"


