[package]
name = "doctavious"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "doctavious"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
directories = { workspace = true }
doctavious-cli = { path = "../../lib/doctavious-cli" }
keyring = "2"
lazy_static = { workspace = true }
remain = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }


[build-dependencies]
built = "0.7"