[package]
name = "cli"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "doctavious"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true, features = ["derive", "env", "string"] }
changelog = { path = "../../lib/changelog" }
directories = { workspace = true }
doctavious-cli = { path = "../../lib/doctavious-cli" }
glob = { workspace  = true }
keyring = { workspace = true }
lazy_static = { workspace = true }
markup = { path = "../../lib/markup" }
regex = { workspace = true }
remain = { workspace = true }
scm = { path = "../../lib/scm" }
serde = { workspace = true }
serde_json = { workspace = true }
shellexpand = { workspace = true }
strum = {workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

[dev-dependencies]
doctavious-std = { path = "../../lib/doctavious-std" }
insta = { workspace = true }
tempfile = { workspace = true }
testing = { path = "../../lib/testing" }

[build-dependencies]
built = "0.7"