[package]
name = "cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "doctavious"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true, features = ["derive", "env", "string"] }
directories = { workspace = true }
doctavious-cli = { path = "../../lib/doctavious-cli" }
glob = { workspace  = true }
keyring = "2"
lazy_static = { workspace = true }
regex = { workspace = true }
remain = { workspace = true }
scm = { path = "../../lib/scm" }
serde = { workspace = true }
serde_json = { workspace = true }
strum = {workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

[dev-dependencies]
common = { path = "../../lib/common" }
insta = { workspace = true }
tempfile = { workspace = true }
testing = { path = "../../lib/testing" }

[build-dependencies]
built = "0.7"