[package]
name = "cli"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "doctavious"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true, features = ["derive", "env", "string"] }
changelog = { path = "../../lib/changelog" }
code-ownify = { path = "../../lib/code-ownify" }
continuous-integration = { path = "../../lib/continuous-integration" }
directories = { workspace = true }
doctavious-cli = { path = "../../lib/doctavious-cli" }
doctavious-std = { path = "../../lib/doctavious-std" }
glob = { workspace  = true }
keyring = { workspace = true }
lazy_static = { workspace = true }
markup = { path = "../../lib/markup" }
regex = { workspace = true }
remain = { workspace = true }
scm = { path = "../../lib/scm" }
serde = { workspace = true }
serde_json = { workspace = true }
shellexpand = { workspace = true }
strum = {workspace = true }
tokio = { workspace = true, features = ["full"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

# TODO: should we we go through SCM???
github-client = { path = "../../lib/third-party/github" }
gitlab-client = { path = "../../lib/third-party/gitlab" }

[dev-dependencies]
insta = { workspace = true }
tempfile = { workspace = true }
testing = { path = "../../lib/testing" }

[build-dependencies]
built = "0.8.0"